#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
DFS-OPERATIONAL-COST-v2.1
=========================

Standalone, account-free audit of an integrable nonconstant zero-cost path in
a two-qubit decoherence-free subspace (DFS).

Frozen physical model
---------------------
    H = (J/2) (X⊗X + Y⊗Y)
    L = sqrt(gamma) (Z⊗I + I⊗Z)
    F_jump(rho) = Tr(L† L rho) >= 0
    E_jump[rho(.)] = integral F_jump(rho(t)) dt

The candidate path begins at |01> and is generated by H.  The declared DFS is
span{|01>, |10>}.  The script tests:

  A. Analytic operator certificate:
       L P_DFS = 0, [H, P_DFS] = 0.

  B. Finite integrable path:
       the state moves a finite trace distance while remaining in the DFS and
       maintaining zero jump cost and zero Lindblad activity.

  C. Tangent/Hessian certificate:
       the path tangent stays in ker(L†L), while a declared transverse
       direction has strictly positive quadratic cost curvature.

     Important: because F is a nonnegative quadratic form, dF=0 at a zero for
     every direction.  First derivatives alone therefore cannot identify the
     zero-cost tangent space.  This audit uses the kernel constraint and the
     second variation.

  D. Transverse perturbation scan:
       psi_epsilon = sqrt(1-epsilon^2)|01> + epsilon|00>
       must obey E_jump(epsilon) proportional to epsilon^2.

  E. Same-meter positive control:
       the same H, L, gamma and duration are applied to
       (|00>+|01>)/sqrt(2), producing positive jump cost and positive
       dissipator activity.  No separate calibration model is used.

  F. Controlled symmetry-breaking scan:
       L_delta = sqrt(gamma)[Z1 + (1+delta)Z2].
       The exact DFS zero occurs at delta=0.  For the same initial state,
       Hamiltonian and duration, the integrated jump cost must open as

           E_jump(delta) = gamma T delta^2,

       and must be even under delta -> -delta.  This converts the ideal DFS
       statement into a tunable zero-point and transverse-scaling diagnostic.

Scientific boundary
-------------------
The result concerns the declared collective-dephasing jump/activity cost.  It
is not a zero-total-energy or zero-control-resource claim, not QPU evidence,
and not by itself a derivation of Lorentzian geometry or a universal
realizability principle.

Run:
    pip install -U numpy scipy matplotlib
    python dfs_operational_cost_v2_1.py

Jupyter/Colab ``-f kernel.json`` arguments are ignored safely.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import importlib.metadata
import json
import math
import os
import platform
import sys
import tempfile
import time
import traceback
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

# Configure Matplotlib before any possible pyplot import.
os.environ.setdefault(
    "MPLCONFIGDIR",
    str(Path(tempfile.gettempdir()) / "dfs_operational_cost_v2_matplotlib"),
)
os.environ.setdefault("MPLBACKEND", "Agg")

import numpy as np
from scipy.integrate import solve_ivp
from scipy.linalg import expm


VERSION = "DFS-OPERATIONAL-COST-v2.1"


@dataclass(frozen=True)
class Config:
    exchange_J: float = 1.0
    collective_gamma: float = 0.20
    duration: float = math.pi / 2.0
    samples: int = 401
    ode_rtol: float = 2.0e-11
    ode_atol: float = 2.0e-13

    operator_tolerance: float = 2.0e-13
    zero_cost_tolerance: float = 2.0e-10
    normalization_tolerance: float = 2.0e-10
    nonconstant_distance_minimum: float = 0.90
    positive_control_cost_minimum: float = 1.0e-3
    positive_activity_minimum: float = 1.0e-3

    epsilon_values: tuple[float, ...] = (
        0.0, 0.01, 0.02, 0.04, 0.08, 0.16, 0.24
    )
    scaling_exponent_interval: tuple[float, float] = (1.995, 2.005)
    transverse_relative_error_tolerance: float = 2.0e-6

    symmetry_breaking_deltas: tuple[float, ...] = (
        -0.08, -0.04, -0.02, -0.01, -0.005,
        0.0,
        0.005, 0.01, 0.02, 0.04, 0.08,
    )
    symmetry_exponent_interval: tuple[float, float] = (1.995, 2.005)
    symmetry_relative_error_tolerance: float = 2.0e-6
    symmetry_evenness_tolerance: float = 2.0e-10


def clean(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(k): clean(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [clean(v) for v in value]
    if isinstance(value, np.ndarray):
        return clean(value.tolist())
    # bool is a subclass of int in Python, so test it before integer types.
    if isinstance(value, (np.bool_, bool)):
        return bool(value)
    if isinstance(value, (np.floating, float)):
        number = float(value)
        return number if math.isfinite(number) else str(number)
    if isinstance(value, (np.integer, int)):
        return int(value)
    return value


def package_version(name: str) -> str | None:
    try:
        return importlib.metadata.version(name)
    except importlib.metadata.PackageNotFoundError:
        return None


def sha256(path: Path | None) -> str | None:
    if path is None:
        return None
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def save_json(path: Path, value: Any) -> None:
    path.write_text(
        json.dumps(clean(value), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def save_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    if not rows:
        return
    with path.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(clean(rows))


def create_unique_output_dir(requested: str | None) -> Path:
    base = Path(
        requested
        or f"dfs_operational_cost_v2_1_{time.strftime('%Y%m%d_%H%M%S')}"
    )
    candidates = [base]
    candidates.extend(
        base.with_name(f"{base.name}_run{index:02d}")
        for index in range(2, 1000)
    )
    for candidate in candidates:
        try:
            candidate.mkdir(parents=True, exist_ok=False)
            if candidate != base:
                print(
                    f"[output] directory exists: {base}\n"
                    f"[output] preserving it; this run uses: {candidate}"
                )
            return candidate
        except FileExistsError:
            continue
    raise RuntimeError(f"Could not allocate an output directory from {base}.")


def ket(index: int, dimension: int = 4) -> np.ndarray:
    value = np.zeros(dimension, dtype=complex)
    value[index] = 1.0
    return value


def projector(state: np.ndarray) -> np.ndarray:
    return np.outer(state, state.conj())


def trace_distance_pure(reference: np.ndarray, state: np.ndarray) -> float:
    overlap = abs(np.vdot(reference, state))
    return float(np.sqrt(max(0.0, 1.0 - min(1.0, overlap * overlap))))


def trace_distance_density(reference: np.ndarray, rho: np.ndarray) -> float:
    difference = 0.5 * (
        (rho - reference) + (rho - reference).conj().T
    )
    return float(0.5 * np.sum(np.abs(np.linalg.eigvalsh(difference))))


def frobenius(matrix: np.ndarray) -> float:
    return float(np.linalg.norm(matrix, ord="fro"))


def hermitian_expectation(operator: np.ndarray, rho: np.ndarray) -> float:
    return float(max(0.0, np.real(np.trace(operator @ rho))))


def dissipator(rho: np.ndarray, jump: np.ndarray) -> np.ndarray:
    kernel = jump.conj().T @ jump
    return jump @ rho @ jump.conj().T - 0.5 * (
        kernel @ rho + rho @ kernel
    )


def build_model(cfg: Config) -> dict[str, np.ndarray]:
    identity = np.eye(2, dtype=complex)
    x = np.array([[0.0, 1.0], [1.0, 0.0]], dtype=complex)
    y = np.array([[0.0, -1.0j], [1.0j, 0.0]], dtype=complex)
    z = np.array([[1.0, 0.0], [0.0, -1.0]], dtype=complex)

    hamiltonian = 0.5 * cfg.exchange_J * (
        np.kron(x, x) + np.kron(y, y)
    )
    z1 = np.kron(z, identity)
    z2 = np.kron(identity, z)
    jump = math.sqrt(cfg.collective_gamma) * (z1 + z2)
    cost_kernel = jump.conj().T @ jump

    state_00 = ket(0)
    state_01 = ket(1)
    state_10 = ket(2)
    state_11 = ket(3)
    p_dfs = projector(state_01) + projector(state_10)
    q_dfs = np.eye(4, dtype=complex) - p_dfs
    return {
        "H": hamiltonian,
        "L": jump,
        "K": cost_kernel,
        "P": p_dfs,
        "Q": q_dfs,
        "Z1": z1,
        "Z2": z2,
        "00": state_00,
        "01": state_01,
        "10": state_10,
        "11": state_11,
    }


def operator_certificate(
    cfg: Config, model: dict[str, np.ndarray]
) -> dict[str, Any]:
    h = model["H"]
    l = model["L"]
    k = model["K"]
    p = model["P"]
    q = model["Q"]

    lp = frobenius(l @ p)
    kp = frobenius(k @ p)
    commutator = frobenius(h @ p - p @ h)
    leakage_block = frobenius(q @ h @ p)
    dfs_rank = int(np.linalg.matrix_rank(p, tol=cfg.operator_tolerance))
    cost_eigenvalues = np.linalg.eigvalsh(k)
    kernel_dimension = int(
        np.count_nonzero(np.abs(cost_eigenvalues) <= cfg.operator_tolerance)
    )
    gates = {
        "L_annihilates_DFS": lp <= cfg.operator_tolerance,
        "cost_kernel_annihilates_DFS": kp <= cfg.operator_tolerance,
        "Hamiltonian_preserves_DFS": (
            commutator <= cfg.operator_tolerance
            and leakage_block <= cfg.operator_tolerance
        ),
        "DFS_equals_cost_kernel_dimension": (
            dfs_rank == 2 and kernel_dimension == 2
        ),
    }
    return {
        "status": (
            "ANALYTIC_DFS_OPERATOR_CERTIFICATE_SUPPORTED"
            if all(gates.values())
            else "ANALYTIC_DFS_OPERATOR_CERTIFICATE_FAILED"
        ),
        "norm_LP_DFS": lp,
        "norm_KP_DFS": kp,
        "norm_commutator_H_P_DFS": commutator,
        "norm_QHP_leakage_block": leakage_block,
        "DFS_rank": dfs_rank,
        "cost_kernel_eigenvalues": cost_eigenvalues,
        "cost_kernel_dimension": kernel_dimension,
        "gates": gates,
    }


def finite_dfs_path(
    cfg: Config, model: dict[str, np.ndarray]
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    h = model["H"]
    l = model["L"]
    k = model["K"]
    q = model["Q"]
    initial = model["01"]
    times = np.linspace(0.0, cfg.duration, cfg.samples)

    rows: list[dict[str, Any]] = []
    jump_rates: list[float] = []
    activity: list[float] = []
    for t in times:
        state = expm(-1.0j * h * t) @ initial
        rho = projector(state)
        velocity = -1.0j * h @ state
        jump_rate = hermitian_expectation(k, rho)
        dissipator_norm = frobenius(dissipator(rho, l))
        leakage = float(np.linalg.norm(q @ state))
        tangent_leakage = float(np.linalg.norm(q @ velocity))
        tangent_kernel_residual = float(np.linalg.norm(k @ velocity))
        rows.append({
            "time": t,
            "trace_distance_from_initial":
                trace_distance_pure(initial, state),
            "jump_rate": jump_rate,
            "dissipator_frobenius": dissipator_norm,
            "DFS_state_leakage": leakage,
            "DFS_tangent_leakage": tangent_leakage,
            "cost_kernel_tangent_residual": tangent_kernel_residual,
            "state_norm_error": abs(float(np.vdot(state, state).real) - 1.0),
        })
        jump_rates.append(jump_rate)
        activity.append(dissipator_norm)

    cumulative_jump = float(np.trapezoid(jump_rates, times))
    cumulative_activity = float(np.trapezoid(activity, times))
    maximum_distance = max(x["trace_distance_from_initial"] for x in rows)
    maximum_leakage = max(x["DFS_state_leakage"] for x in rows)
    maximum_tangent_leakage = max(x["DFS_tangent_leakage"] for x in rows)
    maximum_tangent_kernel = max(
        x["cost_kernel_tangent_residual"] for x in rows
    )
    maximum_norm_error = max(x["state_norm_error"] for x in rows)
    gates = {
        "finite_nonconstant_path": (
            maximum_distance >= cfg.nonconstant_distance_minimum
        ),
        "zero_cumulative_jump_cost": (
            cumulative_jump <= cfg.zero_cost_tolerance
        ),
        "zero_cumulative_dissipator_activity": (
            cumulative_activity <= cfg.zero_cost_tolerance
        ),
        "state_path_stays_in_DFS": (
            maximum_leakage <= cfg.operator_tolerance
        ),
        "path_tangent_stays_in_DFS": (
            maximum_tangent_leakage <= cfg.operator_tolerance
        ),
        "path_tangent_stays_in_cost_kernel": (
            maximum_tangent_kernel <= cfg.operator_tolerance
        ),
        "normalization": (
            maximum_norm_error <= cfg.normalization_tolerance
        ),
    }
    return {
        "status": (
            "FINITE_INTEGRABLE_NONCONSTANT_ZERO_COST_PATH_SUPPORTED"
            if all(gates.values())
            else "FINITE_DFS_PATH_AUDIT_FAILED"
        ),
        "maximum_trace_distance_from_initial": maximum_distance,
        "cumulative_jump_cost": cumulative_jump,
        "cumulative_dissipator_activity": cumulative_activity,
        "maximum_DFS_state_leakage": maximum_leakage,
        "maximum_DFS_tangent_leakage": maximum_tangent_leakage,
        "maximum_cost_kernel_tangent_residual": maximum_tangent_kernel,
        "maximum_norm_error": maximum_norm_error,
        "gates": gates,
    }, rows


def master_trajectory(
    cfg: Config,
    model: dict[str, np.ndarray],
    initial_state: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    h = model["H"]
    l = model["L"]
    initial_rho = projector(initial_state)
    times = np.linspace(0.0, cfg.duration, cfg.samples)

    def rhs(_t: float, flattened: np.ndarray) -> np.ndarray:
        rho = flattened.reshape(4, 4)
        derivative = -1.0j * (h @ rho - rho @ h) + dissipator(rho, l)
        return derivative.reshape(-1)

    solution = solve_ivp(
        rhs,
        (0.0, cfg.duration),
        initial_rho.reshape(-1),
        t_eval=times,
        rtol=cfg.ode_rtol,
        atol=cfg.ode_atol,
    )
    if not solution.success:
        raise RuntimeError(f"Lindblad integration failed: {solution.message}")
    rhos = solution.y.T.reshape(-1, 4, 4)
    return times, rhos


def transverse_scan(
    cfg: Config, model: dict[str, np.ndarray]
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    k = model["K"]
    tangent = model["10"]
    transverse = model["00"]

    tangent_curvature = float(
        2.0 * np.real(np.vdot(tangent, k @ tangent))
    )
    transverse_curvature = float(
        2.0 * np.real(np.vdot(transverse, k @ transverse))
    )
    first_variation_transverse = float(
        2.0 * np.real(np.vdot(transverse, k @ model["01"]))
    )

    rows: list[dict[str, Any]] = []
    for epsilon in cfg.epsilon_values:
        state = (
            math.sqrt(max(0.0, 1.0 - epsilon * epsilon)) * model["01"]
            + epsilon * transverse
        )
        times, rhos = master_trajectory(cfg, model, state)
        rates = np.array(
            [hermitian_expectation(k, rho) for rho in rhos], dtype=float
        )
        numerical_cost = float(np.trapezoid(rates, times))
        predicted_cost = float(
            4.0 * cfg.collective_gamma * cfg.duration * epsilon**2
        )
        absolute_error = abs(numerical_cost - predicted_cost)
        relative_error = (
            absolute_error / predicted_cost
            if predicted_cost > 0.0
            else absolute_error
        )
        rows.append({
            "epsilon": epsilon,
            "numerical_integrated_jump_cost": numerical_cost,
            "analytic_integrated_jump_cost": predicted_cost,
            "absolute_error": absolute_error,
            "relative_error": relative_error,
        })

    positive = [x for x in rows if x["epsilon"] > 0.0]
    exponent, log_prefactor = np.polyfit(
        np.log([x["epsilon"] for x in positive]),
        np.log([x["numerical_integrated_jump_cost"] for x in positive]),
        1,
    )
    maximum_relative_error = max(x["relative_error"] for x in positive)
    gates = {
        "first_variation_is_zero_as_expected_at_quadratic_minimum": (
            abs(first_variation_transverse) <= cfg.operator_tolerance
        ),
        "tangent_second_variation_zero": (
            abs(tangent_curvature) <= cfg.operator_tolerance
        ),
        "transverse_second_variation_positive": (
            transverse_curvature > cfg.positive_control_cost_minimum
        ),
        "quadratic_epsilon_scaling": (
            cfg.scaling_exponent_interval[0]
            <= exponent
            <= cfg.scaling_exponent_interval[1]
        ),
        "analytic_transverse_prediction": (
            maximum_relative_error
            <= cfg.transverse_relative_error_tolerance
        ),
    }
    return {
        "status": (
            "TRANSVERSE_QUADRATIC_COST_BOUNDARY_SUPPORTED"
            if all(gates.values())
            else "TRANSVERSE_COST_AUDIT_FAILED"
        ),
        "first_variation_in_declared_transverse_direction":
            first_variation_transverse,
        "tangent_second_variation": tangent_curvature,
        "transverse_second_variation": transverse_curvature,
        "fitted_epsilon_exponent": float(exponent),
        "fitted_prefactor": float(np.exp(log_prefactor)),
        "analytic_prefactor": (
            4.0 * cfg.collective_gamma * cfg.duration
        ),
        "maximum_positive_epsilon_relative_error": maximum_relative_error,
        "interpretation": (
            "dF=0 does not identify the tangent space at a nonnegative "
            "quadratic zero. The kernel constraint and second variation "
            "separate the zero tangent from the positive transverse direction."
        ),
        "gates": gates,
    }, rows


def positive_control(
    cfg: Config, model: dict[str, np.ndarray]
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    state = (model["00"] + model["01"]) / math.sqrt(2.0)
    times, rhos = master_trajectory(cfg, model, state)
    k = model["K"]
    l = model["L"]
    rows: list[dict[str, Any]] = []
    rates: list[float] = []
    activities: list[float] = []
    trace_errors: list[float] = []
    for t, rho in zip(times, rhos):
        rate = hermitian_expectation(k, rho)
        activity = frobenius(dissipator(rho, l))
        trace_error = abs(float(np.trace(rho).real) - 1.0)
        rates.append(rate)
        activities.append(activity)
        trace_errors.append(trace_error)
        rows.append({
            "time": t,
            "jump_rate": rate,
            "dissipator_frobenius": activity,
            "trace_error": trace_error,
        })

    cumulative_jump = float(np.trapezoid(rates, times))
    cumulative_activity = float(np.trapezoid(activities, times))
    predicted_jump = float(
        2.0 * cfg.collective_gamma * cfg.duration
    )
    relative_error = abs(cumulative_jump - predicted_jump) / predicted_jump
    gates = {
        "same_meter_jump_cost_positive": (
            cumulative_jump >= cfg.positive_control_cost_minimum
        ),
        "same_meter_activity_positive": (
            cumulative_activity >= cfg.positive_activity_minimum
        ),
        "jump_cost_matches_analytic_calibration": (
            relative_error <= cfg.transverse_relative_error_tolerance
        ),
        "trace_preserved": (
            max(trace_errors) <= cfg.normalization_tolerance
        ),
    }
    return {
        "status": (
            "SAME_METER_POSITIVE_CONTROL_SUPPORTED"
            if all(gates.values())
            else "SAME_METER_POSITIVE_CONTROL_FAILED"
        ),
        "initial_state": "(|00>+|01>)/sqrt(2)",
        "cumulative_jump_cost": cumulative_jump,
        "analytic_cumulative_jump_cost": predicted_jump,
        "jump_relative_error": relative_error,
        "cumulative_dissipator_activity": cumulative_activity,
        "maximum_dissipator_activity": max(activities),
        "maximum_trace_error": max(trace_errors),
        "gates": gates,
    }, rows


def symmetry_breaking_scan(
    cfg: Config, model: dict[str, np.ndarray]
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """Open the collective-symmetry-protected zero with a frozen perturbation."""
    rows: list[dict[str, Any]] = []
    initial = model["01"]
    initial_rho = projector(initial)
    p_dfs = model["P"]

    for delta in cfg.symmetry_breaking_deltas:
        jump = math.sqrt(cfg.collective_gamma) * (
            model["Z1"] + (1.0 + delta) * model["Z2"]
        )
        perturbed_model = dict(model)
        perturbed_model["L"] = jump
        perturbed_model["K"] = jump.conj().T @ jump
        times, rhos = master_trajectory(cfg, perturbed_model, initial)

        rates = np.array(
            [
                hermitian_expectation(perturbed_model["K"], rho)
                for rho in rhos
            ],
            dtype=float,
        )
        activities = np.array(
            [frobenius(dissipator(rho, jump)) for rho in rhos],
            dtype=float,
        )
        numerical_cost = float(np.trapezoid(rates, times))
        numerical_activity = float(np.trapezoid(activities, times))
        analytic_cost = float(
            cfg.collective_gamma * cfg.duration * delta**2
        )
        absolute_error = abs(numerical_cost - analytic_cost)
        relative_error = (
            absolute_error / analytic_cost
            if analytic_cost > 0.0
            else absolute_error
        )
        restricted_kernel_residual = frobenius(
            p_dfs @ perturbed_model["K"] @ p_dfs
            - cfg.collective_gamma * delta**2 * p_dfs
        )
        maximum_distance = max(
            trace_distance_density(initial_rho, rho) for rho in rhos
        )
        rows.append({
            "delta": delta,
            "absolute_delta": abs(delta),
            "numerical_integrated_jump_cost": numerical_cost,
            "analytic_integrated_jump_cost": analytic_cost,
            "absolute_error": absolute_error,
            "relative_error": relative_error,
            "integrated_dissipator_activity": numerical_activity,
            "maximum_trace_distance_from_initial": maximum_distance,
            "restricted_kernel_identity_residual":
                restricted_kernel_residual,
        })

    positive = [x for x in rows if x["delta"] > 0.0]
    exponent, log_prefactor = np.polyfit(
        np.log([x["delta"] for x in positive]),
        np.log([x["numerical_integrated_jump_cost"] for x in positive]),
        1,
    )
    by_delta = {round(float(x["delta"]), 12): x for x in rows}
    evenness_errors: list[float] = []
    for row in positive:
        magnitude = round(float(row["delta"]), 12)
        negative = by_delta[-magnitude]["numerical_integrated_jump_cost"]
        scale = max(
            row["numerical_integrated_jump_cost"],
            negative,
            cfg.zero_cost_tolerance,
        )
        evenness_errors.append(
            abs(row["numerical_integrated_jump_cost"] - negative) / scale
        )

    zero_row = by_delta[0.0]
    maximum_relative_error = max(x["relative_error"] for x in positive)
    maximum_evenness_error = max(evenness_errors)
    maximum_restricted_kernel_residual = max(
        x["restricted_kernel_identity_residual"] for x in rows
    )
    gates = {
        "exact_zero_at_collective_symmetry_point": (
            zero_row["numerical_integrated_jump_cost"]
            <= cfg.zero_cost_tolerance
        ),
        "positive_cost_away_from_symmetry_point": all(
            x["numerical_integrated_jump_cost"] > cfg.zero_cost_tolerance
            for x in rows
            if x["delta"] != 0.0
        ),
        "quadratic_symmetry_breaking_scaling": (
            cfg.symmetry_exponent_interval[0]
            <= exponent
            <= cfg.symmetry_exponent_interval[1]
        ),
        "analytic_symmetry_breaking_prediction": (
            maximum_relative_error
            <= cfg.symmetry_relative_error_tolerance
        ),
        "delta_reflection_evenness": (
            maximum_evenness_error <= cfg.symmetry_evenness_tolerance
        ),
        "restricted_cost_kernel_formula": (
            maximum_restricted_kernel_residual
            <= cfg.operator_tolerance
        ),
        "paths_remain_nonconstant": all(
            x["maximum_trace_distance_from_initial"]
            >= cfg.nonconstant_distance_minimum
            for x in rows
        ),
    }
    return {
        "status": (
            "SYMMETRY_PROTECTED_ZERO_AND_QUADRATIC_OPENING_SUPPORTED"
            if all(gates.values())
            else "SYMMETRY_BREAKING_AUDIT_FAILED"
        ),
        "perturbed_jump_operator":
            "L_delta=sqrt(gamma)[Z1+(1+delta)Z2]",
        "analytic_DFS_restriction":
            "P_DFS L_delta^dagger L_delta P_DFS"
            "=gamma delta^2 P_DFS",
        "analytic_path_cost": "E_jump(delta)=gamma T delta^2",
        "fitted_absolute_delta_exponent": float(exponent),
        "fitted_prefactor": float(np.exp(log_prefactor)),
        "analytic_prefactor": cfg.collective_gamma * cfg.duration,
        "zero_point_cost": zero_row["numerical_integrated_jump_cost"],
        "maximum_positive_delta_relative_error": maximum_relative_error,
        "maximum_delta_reflection_evenness_error": maximum_evenness_error,
        "maximum_restricted_kernel_formula_residual":
            maximum_restricted_kernel_residual,
        "gates": gates,
    }, rows


def save_plot(
    path: Path,
    path_rows: list[dict[str, Any]],
    transverse_rows: list[dict[str, Any]],
    control_rows: list[dict[str, Any]],
    symmetry_rows: list[dict[str, Any]],
) -> str | None:
    figure = None
    try:
        import matplotlib.pyplot as plt

        figure, axes = plt.subplots(2, 2, figsize=(10.5, 7.6))
        axes[0, 0].plot(
            [x["time"] for x in path_rows],
            [x["trace_distance_from_initial"] for x in path_rows],
            label="state distance",
        )
        axes[0, 0].plot(
            [x["time"] for x in path_rows],
            [x["jump_rate"] for x in path_rows],
            label="jump cost",
        )
        axes[0, 0].set_title("Finite DFS path")
        axes[0, 0].set_xlabel("time")
        axes[0, 0].legend()

        positive = [x for x in transverse_rows if x["epsilon"] > 0.0]
        axes[0, 1].loglog(
            [x["epsilon"] for x in positive],
            [x["numerical_integrated_jump_cost"] for x in positive],
            "o-",
            label="numerical",
        )
        axes[0, 1].loglog(
            [x["epsilon"] for x in positive],
            [x["analytic_integrated_jump_cost"] for x in positive],
            "--",
            label=r"$\propto\epsilon^2$",
        )
        axes[0, 1].set_title("Transverse cost boundary")
        axes[0, 1].set_xlabel(r"$\epsilon$")
        axes[0, 1].set_ylabel("integrated jump cost")
        axes[0, 1].legend()

        axes[1, 0].plot(
            [x["time"] for x in control_rows],
            [x["jump_rate"] for x in control_rows],
            label="jump rate",
        )
        axes[1, 0].plot(
            [x["time"] for x in control_rows],
            [x["dissipator_frobenius"] for x in control_rows],
            label="dissipator activity",
        )
        axes[1, 0].set_title("Same-meter positive control")
        axes[1, 0].set_xlabel("time")
        axes[1, 0].legend()

        axes[1, 1].plot(
            [x["delta"] for x in symmetry_rows],
            [x["numerical_integrated_jump_cost"] for x in symmetry_rows],
            "o-",
            label="numerical",
        )
        axes[1, 1].plot(
            [x["delta"] for x in symmetry_rows],
            [x["analytic_integrated_jump_cost"] for x in symmetry_rows],
            "--",
            label=r"$\gamma T\delta^2$",
        )
        axes[1, 1].set_title("Symmetry-protected zero")
        axes[1, 1].set_xlabel(r"$\delta$")
        axes[1, 1].set_ylabel("integrated jump cost")
        axes[1, 1].legend()

        for axis in axes.flat:
            axis.grid(True, alpha=0.25)
        figure.tight_layout()
        figure.savefig(path, dpi=180)
        return path.name
    except Exception as exc:
        print(
            "[plot] non-voting plot failed; certificates remain valid: "
            f"{type(exc).__name__}: {exc}"
        )
        return None
    finally:
        if figure is not None:
            try:
                plt.close(figure)
            except Exception:
                pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir")
    raw = sys.argv[1:]
    cleaned: list[str] = []
    ignored: list[str] = []
    index = 0
    while index < len(raw):
        if raw[index] == "-f" and index + 1 < len(raw):
            ignored.extend(raw[index:index + 2])
            index += 2
        elif raw[index].startswith("-f="):
            ignored.append(raw[index])
            index += 1
        else:
            cleaned.append(raw[index])
            index += 1
    if ignored:
        print(f"[notebook] ignored kernel arguments: {ignored}")
    return parser.parse_args(cleaned)


def main() -> None:
    args = parse_args()
    started = time.perf_counter()
    output = create_unique_output_dir(args.output_dir)
    script_value = globals().get("__file__")
    script_path = (
        Path(script_value).resolve()
        if script_value and Path(script_value).is_file()
        else None
    )
    summary: dict[str, Any] = {
        "version": VERSION,
        "status": "RUNNING",
        "provenance": {
            "python": sys.version,
            "platform": platform.platform(),
            "numpy": package_version("numpy"),
            "scipy": package_version("scipy"),
            "matplotlib": package_version("matplotlib"),
            "script_path": str(script_path) if script_path else None,
            "script_sha256": sha256(script_path),
        },
    }
    save_json(output / "summary.json", summary)

    print("\n" + "=" * 96)
    print("DFS OPERATIONAL-COST v2.1 — SYMMETRY-PROTECTED ZERO-MODE AUDIT")
    print("=" * 96)
    print("backend=exact NumPy/SciPy | cloud access=none")

    try:
        cfg = Config()
        model = build_model(cfg)

        print("\n[A] Analytic DFS operator certificate")
        operators = operator_certificate(cfg, model)
        print(json.dumps(clean(operators), indent=2, ensure_ascii=False))

        print("\n[B] Finite nonconstant zero-cost trajectory")
        finite_path, path_rows = finite_dfs_path(cfg, model)
        print(json.dumps(clean(finite_path), indent=2, ensure_ascii=False))

        print("\n[C+D] Tangent/Hessian and transverse epsilon scan")
        transverse, transverse_rows = transverse_scan(cfg, model)
        print(json.dumps(clean(transverse), indent=2, ensure_ascii=False))

        print("\n[E] Same-model, same-meter positive control")
        control, control_rows = positive_control(cfg, model)
        print(json.dumps(clean(control), indent=2, ensure_ascii=False))

        print("\n[F] Controlled collective-symmetry breaking")
        symmetry, symmetry_rows = symmetry_breaking_scan(cfg, model)
        print(json.dumps(clean(symmetry), indent=2, ensure_ascii=False))

        global_gates = {
            "analytic_DFS_kernel_and_invariance":
                operators["status"]
                == "ANALYTIC_DFS_OPERATOR_CERTIFICATE_SUPPORTED",
            "finite_integrable_nonconstant_zero_cost_path":
                finite_path["status"]
                == "FINITE_INTEGRABLE_NONCONSTANT_ZERO_COST_PATH_SUPPORTED",
            "quadratic_transverse_cost_boundary":
                transverse["status"]
                == "TRANSVERSE_QUADRATIC_COST_BOUNDARY_SUPPORTED",
            "same_meter_positive_control":
                control["status"]
                == "SAME_METER_POSITIVE_CONTROL_SUPPORTED",
            "symmetry_protected_zero_and_quadratic_opening":
                symmetry["status"]
                == "SYMMETRY_PROTECTED_ZERO_AND_QUADRATIC_OPENING_SUPPORTED",
        }
        physical_support = all(global_gates.values())
        scientific_status = (
            "DFS_SYMMETRY_PROTECTED_OPERATIONAL_ZERO_MODE_SUPPORTED"
            if physical_support
            else "DFS_OPERATIONAL_ZERO_MODE_AUDIT_FAILED"
        )
        certificate = {
            "version": VERSION,
            "scientific_status": scientific_status,
            "physical_support": physical_support,
            "frozen_cost_definition": {
                "Hamiltonian": "(J/2)(XX+YY)",
                "jump_operator": "sqrt(gamma)(Z1+Z2)",
                "local_cost": "F_jump(rho)=Tr(L^dagger L rho)",
                "path_cost": "E_jump=integral F_jump dt",
                "parameters": asdict(cfg),
                "meter_freezing": (
                    "H, L, gamma and duration are identical for the candidate, "
                    "transverse scan and positive control."
                ),
            },
            "operator_certificate": operators,
            "finite_path": finite_path,
            "transverse_boundary": transverse,
            "positive_control": control,
            "symmetry_breaking": symmetry,
            "global_gates": global_gates,
            "claim_boundary": (
                "This exact two-qubit model supports a nonconstant finite path "
                "inside the kernel of a predeclared collective-dephasing jump "
                "cost. The same frozen meter gives quadratic positive cost "
                "transverse to the DFS and positive cost/activity on a control. "
                "A controlled imbalance of the collective coupling opens the "
                "zero as E(delta)=gamma T delta^2. "
                "This is not zero total energy, QPU evidence, a universal "
                "realizability theorem, or a derivation of Lorentzian signature."
            ),
        }

        save_json(output / "dfs_v2_certificate.json", certificate)
        save_csv(output / "dfs_finite_path.csv", path_rows)
        save_csv(output / "dfs_transverse_scan.csv", transverse_rows)
        save_csv(output / "dfs_positive_control.csv", control_rows)
        save_csv(output / "dfs_symmetry_breaking_scan.csv", symmetry_rows)
        figure = save_plot(
            output / "dfs_v2_diagnostic.png",
            path_rows,
            transverse_rows,
            control_rows,
            symmetry_rows,
        )

        summary.update({
            "status": "COMPLETE",
            "scientific_status": scientific_status,
            "physical_support": physical_support,
            "outputs": {
                "certificate": "dfs_v2_certificate.json",
                "finite_path": "dfs_finite_path.csv",
                "transverse_scan": "dfs_transverse_scan.csv",
                "positive_control": "dfs_positive_control.csv",
                "symmetry_breaking_scan":
                    "dfs_symmetry_breaking_scan.csv",
                "figure": figure,
            },
        })

        print("\n" + "=" * 96)
        print("GLOBAL VERDICT")
        print("=" * 96)
        print(json.dumps(clean({
            "scientific_status": scientific_status,
            "physical_support": physical_support,
            "global_gates": global_gates,
            "claim_boundary": certificate["claim_boundary"],
        }), indent=2, ensure_ascii=False))

        if not physical_support:
            raise AssertionError(
                "At least one frozen DFS-v2 gate failed; inspect certificate."
            )
    except Exception as exc:
        summary.update({
            "status": "FAIL",
            "error_type": type(exc).__name__,
            "error": str(exc),
            "traceback": traceback.format_exc(),
        })
        raise
    finally:
        summary["elapsed_seconds"] = time.perf_counter() - started
        save_json(output / "summary.json", summary)
        print(f"elapsed={summary['elapsed_seconds']:.2f}s")
        print(f"outputs={output}")


if __name__ == "__main__":
    main()
